apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-address = "127.0.0.1:8088"
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
    [http]
      enabled = true
      auth-enabled = false
      bind-address = ":8086"
    [[graphite]]
      enabled = false
      database = "telegraf"
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  labels:
    app: influxdb
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: admin
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: pass
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb-grafana
spec:
  ports:
    - port: 8086
  selector:
    app: influxdb-grafana
    tier: influxdb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb-grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb-grafana
    tier: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb-grafana
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-grafana
        tier: influxdb
    spec:
      containers:
      - image: my-influxdb
        name: my-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        - name: influxdb-conf
          subPath: influxdb.conf
          mountPath: /etc/influxdb/influxdb.conf
          readOnly: true
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: influxdb-conf
        configMap:
          name: influxdb-config
