apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-wordpress-phpmyadmin
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-wordpress-phpmyadmin
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-wordpress-phpmyadmin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-wordpress-phpmyadmin
spec:
  selector:
    matchLabels:
      app: mysql-wordpress-phpmyadmin
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-wordpress-phpmyadmin
        tier: mysql
    spec:
      containers:
      - image: my-mysql
        name: my-mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
          name: my-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc