apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: mysql-wordpress-phpmyadmin
spec:
  ports:
    - port: 5000
  selector:
    app: mysql-wordpress-phpmyadmin
    tier: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: mysql-wordpress-phpmyadmin
spec:
  selector:
    matchLabels:
      app: mysql-wordpress-phpmyadmin
      tier: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-wordpress-phpmyadmin
        tier: phpmyadmin
    spec:
      containers:
      - image: my-phpmyadmin
        name: my-phpmyadmin
        imagePullPolicy: Never
        env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 5000
          name: phpmyadmin