apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false
    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################
    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"
    ###############################################################################
    #                            INPUT PLUGINS                                    #
    ###############################################################################
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_name_include = []
      perdevice = true
      total = true
      docker_label_include = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: influxdb-grafana
    tier: telegraf
spec:
  ports:
    - port: 8125
      protocol: UDP
      targetPort: 8125        
  selector:
    app: influxdb-grafana
    tier: telegraf
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  
spec:
  selector:
    matchLabels:
      app: influxdb-grafana
      tier: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb-grafana
        tier: telegraf
    spec:
      containers:
        - image: my-telegraf
          name: my-telegraf
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: telegraf-secrets
          volumeMounts:
            - name: telegraf-data
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf-data
          configMap:
            name: telegraf-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
